---
- hosts: 172.31.37.88
  become: yes
  tasks:
   - include_tasks: myfile.yml
   - name : i want to install webserver
     apt:
       name: apache2
   - name: copy index file into node side
     copy:
       src: myindexfile
       dest: /var/www/html/index.html

   - name: i want download iternet files
     get_url:
         url: https://example.com/path/file.conf
         dest: /home/ubuntu/
     force_basic_auth: yes    

   - name: i want to install dynamic file into nodes
     template:
         src: myindex.j2
         dest: /var/www/html/index.html
         notify: restartwebseerever

     handlers:
   - name: restartwebseerever
     service:
      name: apache2
      state: restarted



